### PR TITLE
commontable: Fixes #111, support dependent destroy

### LINKED ISSUE #111: How dependent destroy on comments will work
I want to delete all comments thread as my post delete. Please tell me how can we dependent destroy the comments

### PR DESCRIPTION
**Pull request by mulander**
Signed-off-by: Adam Wolk <adam.wolk@koparo.com>

### CODE REVIEW

**Comment by mulander** [comment]
This branch implements an ability to define dependant: :destroy on the has_one association between a commontable and the commontator thread.

More details in #111.

**Comment by Dantemss** [comment]
Thanks for the PR. I think I'll make a small tweak so the destroy option is part of the options hash (as I said in https://github.com/lml/commontator/issues/111).

**Comment by mulander** [comment]
Thanks for the reply, yeah that tweak sounds good.

**Comment by mulander** [comment]
@Dantemss sorry it took this long. The last two commits adhere to your suggestion of reusing the options hash as noted in #111.

**Comment by Dantemss** [comment]
Thanks for the PR

**Pull request merged**
